blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://wa.me/5581996703931?text=Estou%20com%20dúvidas%20nos%20templates%20do%20repositório.
    about: Dúvidas sobre o template, favor entrar em contato.
